PR-3041 Update dependencies
asfadmin/thin-egress-app pull request #443
Opened 2022-01-24 17:25 UTC by reweeden

Might be a good idea to pin dependency versions with `pip-tools` or `pipenv`. These tools will automatically pin the entire dependency tree in order to produce deterministic builds. They also both provide a single command upgrade mechanism to pin everything to the latest version.

2022-01-25 20:49 UTC, Jlrine2 approved these changes

2022-01-25 23:46 UTC, Jlrine2 commented
PR looks like it was based of master, requirements are now in `/requirements.txt` and `/requirements-dev.txt`

2022-01-25 23:46 UTC, Jlrine2 requested changes
^

2022-01-26 17:15 UTC, reweeden commented
> PR looks like it was based of master, requirements are now in `/requirements.txt` and `/requirements-dev.txt`

No it was based on devel. The requirements.txt was relocated in #440 which wasn't merged at the time.

2022-01-26 17:47 UTC, Jlrine2 approved these changes

2022-01-26 17:47 UTC, merged