Use JWT and UserProfile classes provided by rain-api-core.auth
asfadmin/thin-egress-app pull request #506
Opened 2022-03-29 00:16 UTC by Jlrine2

2022-03-29 21:58 UTC, Jlrine2 commented
created an [issue](https://github.com/ASFHyP3/mkdocs-asf-theme/issues/27) in mkdocs-asf-theme for the security vulnerability in mkdocs-material. we can pin the version to 7.1.6 ourselves too if we want

2022-03-29 22:12 UTC, reweeden requested changes
Nice! I like that ratio of additions to deletions

2022-03-29 22:12 UTC, reweeden commented on lambda/app.py
> +            log.debug(f'User {user_profile.user_id} has user profile: {user_profile.to_jwt_payload()}')
Use the `%s` in log message strings and pass the values as args

2022-03-29 22:12 UTC, reweeden commented on lambda/app.py
> +                JWT_MANAGER.get_header_to_set_auth_cookie(user_profile, os.getenv('COOKIE_DOMAIN', '')))
```suggestion
            custom_headers.update(
                JWT_MANAGER.get_header_to_set_auth_cookie(user_profile, os.getenv('COOKIE_DOMAIN', ''))
            )
```

2022-03-29 22:12 UTC, reweeden commented on tests/test_app.py
> +            "profile": user_profile.to_jwt_payload()
I'd prefer having a hardcoded dict here just in case the behavior of `to_jwt_payload` changes.

2022-03-29 22:45 UTC, benbart approved these changes

2022-03-29 22:51 UTC, Jlrine2 commented on lambda/app.py
> +JWT_KEYS = retrieve_secret(os.getenv('JWT_KEY_SECRET_NAME'))
I agree, just wasn't sure how I wanted to go about that.

2022-03-29 22:52 UTC, Jlrine2 commented on lambda/app.py
> +JWT_MANAGER = JwtManager(**AUTH_CONFIG)
good catch

2022-03-30 17:59 UTC, Jlrine2 commented on lambda/app.py
> +JWT_KEYS = retrieve_secret(os.getenv('JWT_KEY_SECRET_NAME'))
We could set expensive globals to `None` and then call a function at the beginning of `TeaChalice.__call__` that updates them using `ttl_cache` to save on performance. Not sure how I feel about that tho

2022-03-30 21:37 UTC, reweeden commented on lambda/app.py
> +        return json.loads(response)['blacklist']
Do we need to do any error handling in case the blacklist file is malformed?

2022-03-30 21:37 UTC, reweeden commented on tests/test_app.py
> +                'urs-access-token': 'test_token',
Ahhh, half are single and half are double, pls no.

2022-04-05 22:39 UTC, benbart approved these changes

2022-04-05 22:45 UTC, merged