PR-4559 Update S3 docs to include multipart_chunksize guidance
asfadmin/thin-egress-app pull request #729
Opened 2023-06-05 17:18 UTC by mattp0

Update docs to include multipart_chunksize guidance in readme and update python example to use transfer_config object

2023-06-05 17:28 UTC, reweeden requested changes

2023-06-05 17:28 UTC, reweeden commented on docs/s3access.md
> +MB = 1024 ** 2
Pretty sure
```suggestion
MiB = 1024 ** 2
```

2023-06-05 17:28 UTC, reweeden commented on docs/s3access.md
> +The AWS multipart_chunksize by default is 8MB, it is recommended that a multipart_chucksize of 128MB-1GB is used. This is included in the example below. Addtional resources can be found from [AWS](ht
Is it MB or MiB?

2023-06-05 19:52 UTC, mattp0 commented on docs/s3access.md
> +MB = 1024 ** 2
there is not direct guidance from AWS on what the unit is. I think in this case I did use a power of 2 for the 1024 so it should be MiB.

2023-06-05 19:54 UTC, mattp0 commented on docs/s3access.md
> +The AWS multipart_chunksize by default is 8MB, it is recommended that a multipart_chucksize of 128MB-1GB is used. This is included in the example below. Addtional resources can be found from [AWS](ht
the docs are showing examples with MB. so I should swap my top to be 1000?. 1MB = 1000 Kb and 1MiB = 1024 Kib.

2023-06-05 20:02 UTC, mattp0 commented on docs/s3access.md
> +MB = 1024 ** 2
I updated it to be 1000 and use MB as the docs from AWS do.

2023-06-05 20:36 UTC, reweeden commented on docs/s3access.md
> +        multipart_chunksize= 128 * MB
PEP 8
```suggestion
        multipart_chunksize = 128 * MB
```

2023-06-06 14:53 UTC, reweeden requested changes
Another thing to consider is if this change actually belongs in TEA or if it would be better made to our sentinel1 templates. Do we actually know that the larger chunk size is better for ALL DAACs? Or is this just an optimization for our Sentinel archive because we distribute everything as one large zip file? We have to make sure that the changes that make it into this repository would be correct for any DAAC that might enable s3 direct access through TEA, now and in the future.

2023-06-06 14:53 UTC, reweeden commented on docs/s3access.md
> +The AWS `multipart_chunksize` by default is 8MB, it is recommended that a `multipart_chuncksize` of 128MB-1GB is used. This is included in the example below. Additional resources can be found from [A
Still misspelled
```suggestion
The AWS `multipart_chunksize` by default is 8MB, it is recommended that a `multipart_chunksize` of 128MB-1GB is used. This is included in the example below. Additional resources can be found from [AWS](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html#configuration-values)
```

2023-06-06 14:53 UTC, reweeden commented on docs/s3access.md
> +The AWS `multipart_chunksize` by default is 8MB, it is recommended that a `multipart_chuncksize` of 128MB-1GB is used. This is included in the example below. Additional resources can be found from [A
```suggestion
The AWS `multipart_chunksize` by default is 8MB, it is recommended that a `multipart_chuncksize` of 128MB-1GB is used. This is included in the example below. Additional resources can be found from [AWS](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html#configuration-values).
```

2023-06-06 14:53 UTC, reweeden commented on docs/s3access.md
> +The AWS `multipart_chunksize` by default is 8MB, it is recommended that a `multipart_chuncksize` of 128MB-1GB is used. This is included in the example below. Additional resources can be found from [A
I find some of the phrasing/punctuation to be a bit awkward. Maybe something like this would be better. I also wonder if we should be explaining why the bigger limit is better?
```suggestion
The AWS `multipart_chunksize` is 8MB by default. It is recommended to increase this to between 128MB-1GB as shown in the example below. Additional resources can be found in the [AWS documentation](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html#configuration-values)
```

2023-06-06 15:46 UTC, mattp0 commented
> Another thing to consider is if this change actually belongs in TEA or if it would be better made to our sentinel1 templates. Do we actually know that the larger chunk size is better for ALL DAACs? Or is this just an optimization for our Sentinel archive because we distribute everything as one large zip file? We have to make sure that the changes that make it into this repository would be correct for any DAAC that might enable s3 direct access through TEA, now and in the future.

In my understanding this is a challenge that all DAACs will face as this request relates directly to lowering the number of logs generated for distribution metrics. As the file size was too large for the team to ingest on the NASA side of the house. I think it makes sense to put in TEA and maybe I should add some extra text about the rationale?

2023-06-06 20:07 UTC, closed without merging